# Generated by Django 5.0.3 on 2024-04-03 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminAccount',
        ),
        migrations.DeleteModel(
            name='InstructorAccount',
        ),
    ]
