# Generated by Django 5.0.3 on 2024-04-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_adminaccount_delete_instructoraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='status',
            field=models.CharField(default=4, max_length=50),
            preserve_default=False,
        ),
    ]
