# Generated by Django 5.0.3 on 2024-04-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_instructor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='education_level',
            field=models.CharField(choices=[('Cử nhân', 'Cử nhân'), ('Thạc sĩ', 'Thạc sĩ'), ('Tiến sĩ', 'Tiến sĩ')], max_length=100),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='job_position',
            field=models.CharField(choices=[('Trợ giảng', 'Trợ giảng'), ('Giảng viên', 'Giảng viên'), ('Phó giáo sư', 'Phó giáo sư'), ('Giáo sư', 'Giáo sư')], max_length=100),
        ),
    ]
