# Generated by Django 5.0.3 on 2024-04-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_instructor_education_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='status',
            field=models.CharField(choices=[('Đang dạy', 'Đang dạy'), ('Nghỉ hưu', 'Nghỉ hưu'), ('Nghỉ việc', 'Nghỉ việc'), ('Hợp đồng', 'Hợp đồng'), ('Nghỉ phép', 'Nghỉ phép')], max_length=50),
        ),
    ]
