# Generated by Django 5.0.1 on 2024-04-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_instructor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='instructorID',
            field=models.CharField(editable=False, max_length=7, primary_key=True, serialize=False),
        ),
    ]
